#!/usr/bin/env bash
self=$(readlink -f $0); tasks=`dirname ${self}`; projectRoot=`dirname ${tasks}`;
docker build -t justinvanwinkle/datagrip:latest -t justinvanwinkle/datagrip:`date +%Y%m%d` -f Dockerfile.datagrip $projectRoot;



